### ISSUE TITLE
Missing extensions since V4.0

### ISSUE THREAD

**Issue by RoboMagus** [linuxserver/docker-code-server#101]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When searching for code-server extensions results should pop up.

## Current Behavior

Starting with V4.0 the list of search results for extensions is incomplete when compared to V3.12.
Similarly, installing plugins through cli with their respective identifiers fails, where in V3.12 there was no issue.
(Regardless of using the newly added helper script)

## Steps to Reproduce

1. Spin up a container for `linuxserver/code-server:3.12.0`
2. Search for extension, e.g. 'keesschollaart.vscode-home-assistant'
3. You can find and install it.
4. Now spin up a new container with a newer version: `linuxserver/code-server:4.0.2`
5. Perform the same extension search as in step 2
6. No results found...

Similar verification through commandline installation.

## Environment
**OS:** Windows & Linux
**CPU architecture:** x86_64 & arm32
**How docker service was installed:**

Windows: docker-desktop
Linux: Curl helper script

## Command used to create docker container (run/create/compose/screenshot)

compose: 
```yaml


  code-server:
    image: linuxserver/code-server
    container_name: code-server
    restart: unless-stopped
    volumes:
      - ./Volumes/code-server/config:/config
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - DEFAULT_WORKSPACE=/docker-stack
```

## Docker logs

Unavailable at time of writing. Will add later in case information above proves insufficient.
