### ISSUE TITLE
No accounts requested yet

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-code-server#117]
------------------------------

## Expected Behavior
![image](https://user-images.githubusercontent.com/4349962/185006994-324180b9-7c70-4b9e-a1ce-1f250f1624d0.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/4349962/185006947-927035ef-d1cf-4a26-95ad-05015f615b6d.png)
Source control works. Have added Github SSH keys, permissions 600 and did global username and email.
Everything else seems to work as expected.
Have tried with and without $PASSWORD set.

## Steps to Reproduce
1. Click on Accounts button

## Environment
**OS:** Ubuntu 20.04.4
**CPU architecture:** x86_64
**How docker service was installed:**
```
  code-server:
    image: linuxserver/code-server
    container_name: Code-Server
    hostname: Code-Server
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - PASSWORD= #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code.$DOMAINNAME #optional
      - DOCKER_MODS=linuxserver/mods:code-server-docker
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $USERDIR/CodeServer:/config
      - $DOCKERDIR:/DockerHDA
      - /var/run/docker.sock:/var/run/docker.sock
    networks: #Prevents Docker from creating a default stack network
      pihole:
        ipv4_address: '172.22.0.131'
    ports:
      - 8443:8443
    labels: 
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.code-server-rtr.entrypoints=https"
      - "traefik.http.routers.code-server-rtr.rule=Host(`code.$DOMAINNAME`)"
     # - "traefik.http.routers.code-server-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.code-server-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.code-server-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.code-server-rtr.service=code-server-svc"
      - "traefik.http.services.code-server-svc.loadbalancer.server.port=8443"
      ## Flame Dashboard
      - flame.type=application # "app" works too
      - flame.name=Code Server
      - flame.category=Coding
      - flame.icon=https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/vscode.png # Optional, default is "docker"
    healthcheck:
      test: curl -fSs 127.0.0.1:8443/healthz || exit 1
      start_period: 60s
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
```

## Docker logs
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:code-server-docker files to container
[mod-init] linuxserver/mods:code-server-docker applied to container
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    997
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
setting permissions::configuration
setting permissions::workspace
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/98-docker
**** installing docker and docker compose ****
Copying over docker and docker-compose binaries

***********************************************************
***********************************************************
****                                                   ****
****                                                   ****
**** This mod "linuxserver/mods:code-server-docker"    ****
****                                                   ****
****                                                   ****
**** has been deprecated and will not receive updates  ****
****                                                   ****
****                                                   ****
****     Please switch to the universal version:       ****
****                                                   ****
****       "linuxserver/mods:universal-docker"         ****
****                                                   ****
****                                                   ****
***********************************************************
***********************************************************
cont-init: info: /etc/cont-init.d/98-docker exited 0
cont-init: info: running /etc/cont-init.d/99-custom-scripts
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun code-server (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
starting with no password
[2022-08-17T00:21:18.953Z] info  code-server 4.5.2 35372d3832521d25327e11c9776096730df22ecb
[2022-08-17T00:21:18.954Z] info  Using user-data-dir ~/data
[2022-08-17T00:21:18.967Z] info  Using config file ~/.config/code-server/config.yaml
[2022-08-17T00:21:18.967Z] info  HTTP server listening on http://0.0.0.0:8443/
[2022-08-17T00:21:18.967Z] info    - Authentication is disabled
[2022-08-17T00:21:18.967Z] info    - Not serving HTTPS
[2022-08-17T00:21:18.967Z] info    - Proxying the following domain:
[2022-08-17T00:21:18.967Z] info      - *.code.mydomain.com
[01:21:28] Extension host agent started.
[01:21:28] [172.22.0.114][dd65bc15][ManagementConnection] Unknown reconnection token (never seen).
[01:21:29] Deleted from disk felipecaputo.git-project-manager /config/extensions/felipecaputo.git-project-manager-1.8.2
[01:21:29] Deleted from disk donjayamanne.githistory /config/extensions/donjayamanne.githistory-0.6.19
[01:21:29] Deleted from disk shan.code-settings-sync /config/extensions/shan.code-settings-sync-3.4.3
[01:21:29] [172.22.0.114][91000585][ExtensionHostConnection] Unknown reconnection token (never seen).
[01:21:29] [172.22.0.114][5e23317b][ManagementConnection] Unknown reconnection token (never seen).
[01:21:29] [172.22.0.114][adf14dfa][ExtensionHostConnection] Unknown reconnection token (never seen).
```
