### ISSUE TITLE
[kompose] <kompose doesn't work on the docker-compose file?>

### ISSUE THREAD

**Issue by zhh210** [linuxserver/docker-code-server#171]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'm new to kompose but find it very helpful for converting docker compose to k8s. However, when trying it out on the recommended docler-compose file:
```
---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```
I got error of:

```
(base) [ec2-user@ip-10-10-98-2 kompose]$ kompose convert --provider kubernetes -f codeserver.yaml 
ERRO Could not parse config for project kompose : Unsupported config option for services service: 'code-server' 
FATA composeObject.Parse() failed, Failed to load compose file: Unsupported config option for services service: 'code-server' 
```

I don't see any existing issues/questions so I think it might be worth creating an issue here.

### Reason for change

Makes it easier for deployment to k8s
