### ISSUE TITLE
Passwords not being set

### ISSUE THREAD

**Issue by TheGreatestJannet** [linuxserver/docker-code-server#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The password is not being set. I keep getting `starting with no password` despite the password being set in the both the docker-compose file as well as the code-server config file where the password is hashed. Nether of them work.
------------------------------

## Expected Behavior

The password should be set.

## Current Behavior

The password is not set and anyone can access code-server.

## Steps to Reproduce

1.Set a password and start the container
2.Access the container and see that no password is asked for.

## Environment
**OS:** Raspberry Pi OS
**CPU architecture:** arm32
**How docker service was installed:** Official Repo

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - PASSWORD=password
      #- SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=code-server.example.org
      - DOCKER_MODS=linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-php
    volumes:
      - /home/user/code-server/config:/config
      - /var/www:/livewebsite
    ports:
      - 8445:8443
    restart: unless-stopped
```
## Docker logs

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
setting up sudo access
setting sudo password using SUDO_PASSWORD env var
Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully
[cont-init.d] 30-config: exited 0.
[cont-init.d] 98-php: executing... 
**** installing php and composer ****
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Hit:5 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:6 https://dl.yarnpkg.com/debian stable InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
composer is already the newest version (1.6.3-1).
php7.2 is already the newest version (7.2.24-0ubuntu0.18.04.7).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
[cont-init.d] 98-php: exited 0.
[cont-init.d] 98-python3: executing... 
**** installing python3 dev environment ****
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Hit:5 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:6 https://dl.yarnpkg.com/debian stable InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.7).
python3-dev is already the newest version (3.6.7-1~18.04).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.4).
python3-venv is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
[cont-init.d] 98-python3: exited 0.
[cont-init.d] 98-shellcheck: executing... 
**** installing shellcheck ****
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Hit:5 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:6 https://dl.yarnpkg.com/debian stable InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
shellcheck is already the newest version (0.4.6-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
[cont-init.d] 98-shellcheck: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
starting with no password
[2021-02-03T12:18:44.036Z] info  code-server 3.8.0 c4610f7829701aadb045d450013b84491c30580d
[2021-02-03T12:18:44.039Z] info  Using user-data-dir ~/data
[2021-02-03T12:18:44.078Z] info  Using config file ~/.config/code-server/config.yaml
[2021-02-03T12:18:44.079Z] info  HTTP server listening on http://0.0.0.0:8443 
[2021-02-03T12:18:44.079Z] info    - Authentication is disabled 
[2021-02-03T12:18:44.079Z] info    - Not serving HTTPS 
[2021-02-03T12:18:44.080Z] info    - Proxying the following domain:
[2021-02-03T12:18:44.080Z] info      - *.code-server.example.org
```
