### ISSUE TITLE
Error 403 on Extension view/download/install

### ISSUE THREAD

**Issue by behnam-io** [linuxserver/docker-code-server#57]
I made a fresh install of code-server using docker-compose, but getting 403 Error on Extensions tab

------------------------------

## Expected Behavior
I assume checking marketplace extensions and download/installing them should be similar to vs code

## Current Behavior

Error on opening any extension page

![image](https://user-images.githubusercontent.com/75466482/109413639-b1975280-79c3-11eb-80b9-ec4430185147.png)

Error on download/installing any extension

![image](https://user-images.githubusercontent.com/75466482/109413669-d390d500-79c3-11eb-8afd-36e86e4b5724.png)

Logged Errors

```
[2021-02-28 12:52:14.985] [window] [error] Error: Server returned 403
    at Object.t.asText (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1936:111)
    at V.getManifest (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:2120:377)
    at async w.installFromGallery (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4251:98)
    at async e.installFromGallery (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4436:931)
[2021-02-28 12:52:14.997] [window] [error] Server returned 403: Error: Server returned 403
    at Object.t.asText (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:1936:111)
    at V.getManifest (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:2120:377)
    at async w.installFromGallery (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4251:98)
    at async e.installFromGallery (https://vscode.mydomain.com/static/fc6d123da59a4e5a675ac8e080f66e032ba01a1b/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js:4436:931)
```

## Steps to Reproduce

1. Used root user and created `/docker-confs` directory and `/docker-confs/docker-compose.yml` file
2. create a live container using docker-compose (and swag). containers up and running
```yaml
version: "2"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tehran
      - URL=mydomain.com
      - SUBDOMAINS=vscode
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=contact@mydomain.com #optional
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
      - EXTRA_DOMAINS=
    volumes:
      - /docker-confs/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tehran
      - PASSWORD=xxxxx #optional
      - SUDO_PASSWORD=xxxxx #optional
    volumes:
      - /docker-confs/code-server/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```
3. setup reverse-proxy for code-server container using proxy-confs in swag configs (templae from /config/nginx/proxy-confs/code-server.subdomain.conf)
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name vscode.* "~^[0-9]{1,10}\.code-server\..*$";

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app code-server;
        set $upstream_port 8443;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```
4. login to vscode.mydomain.com and try to open any extension in extensions tab

## Environment
**OS:** Centos7
**CPU architecture:**64
**How docker service was installed:**  from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose up -d`

## Docker logs
```
error Unauthorized Error: Unauthorized
    at new HttpError (/usr/local/share/.config/yarn/global/node_modules/code-server/out/common/http.js:34:28)
    at ensureAuthenticated (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/http.js:44:15)
    at wrapped (/usr/local/share/.config/yarn/global/node_modules/code-server/out/node/wsRouter.js:81:24)
    at Layer.handle [as handle_request] (/usr/local/share/.config/yarn/global/node_modules/router/lib/layer.js:102:15)
    at next (/usr/local/share/.config/yarn/global/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/usr/local/share/.config/yarn/global/node_modules/router/lib/route.js:109:3)
    at handle (/usr/local/share/.config/yarn/global/node_modules/router/index.js:515:11)
    at Layer.handle [as handle_request] (/usr/local/share/.config/yarn/global/node_modules/router/lib/layer.js:102:15)
    at /usr/local/share/.config/yarn/global/node_modules/router/index.js:291:22
    at Function.process_params (/usr/local/share/.config/yarn/global/node_modules/router/index.js:349:12)
```
