### ISSUE TITLE
login failed when pass PASSWORD using FILE__PASSWORD

### ISSUE THREAD

**Issue by NigelBoxing** [linuxserver/docker-code-server#63]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

login success with password set in file
## Current Behavior

login failed
## Steps to Reproduce

1. use FILE__PASSWORD in docker-compose.yml
```yaml
services:
  app:
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - FILE__PASSWORD=/run/secrets/password
      - FILE__SUDO_PASSWORD=/run/secrets/sudopassword
    secrets:
      - password
      - sudopassword
secrets:
  password:
    file: ./password.txt
  sudopassword:
    file: ./sudopassword.txt
```
2. docker logs code-server
```bash
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
setting up sudo access
adding abc to sudoers
setting sudo password using SUDO_PASSWORD env var
Enter new UNIX password: Retype new UNIX password: Sorry, passwords do not match
passwd: Authentication token manipulation error
passwd: password unchanged
[cont-init.d] 30-config: exited 0.
```
3. when i use the password set in password.txt , code-server web page pops 'Incorrect password'
## Environment
**OS:** CentOS 7.9
**CPU architecture:** x86_64
**How docker service was installed:**

from official docker repo
## Command used to create docker container (run/create/compose/screenshot)

docker-compose up -d
## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[env-init] PASSWORD set from FILE__PASSWORD
[env-init] SUDO_PASSWORD set from FILE__SUDO_PASSWORD
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

User uid:    1000
User gid:    1000

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
setting up sudo access
adding abc to sudoers
setting sudo password using SUDO_PASSWORD env var
Enter new UNIX password: Retype new UNIX password: Sorry, passwords do not match
passwd: Authentication token manipulation error
passwd: password unchanged
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-04-06T11:41:54.008Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2021-04-06T11:41:55.217Z] info  code-server 3.9.2 109d2ce3247869eaeab67aa7e5423503ec9eb859
[2021-04-06T11:41:55.220Z] info  Using user-data-dir ~/data
[2021-04-06T11:41:55.261Z] info  Using config file ~/.config/code-server/config.yaml
[2021-04-06T11:41:55.261Z] info  HTTP server listening on http://0.0.0.0:8443
[2021-04-06T11:41:55.261Z] info    - Authentication is enabled
[2021-04-06T11:41:55.262Z] info      - Using password from $PASSWORD
[2021-04-06T11:41:55.262Z] info    - Not serving HTTPS
