### ISSUE TITLE
Permission denied while saving a file

### ISSUE THREAD

**Issue by Nefcanto** [linuxserver/docker-code-server#79]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
File should be saved

## Current Behavior
File is not saved and I receive this error:

> Failed to save 'TicketController.cs': Unable to write file 'vscode-remote://0.0.0.0:8443/Company/AdminApi/Api/Controllers/TicketController.cs' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Company/AdminApi/Api/Controllers/TicketController.cs')

## Steps to Reproduce

1. Use your own `docker-compose.yml` content in your [docker hub repo](https://hub.docker.com/r/linuxserver/code-server)
2. Mount a simple project (any project, any directory)
3. `docker-compose up`
4. Go to `localhost:8443`
5. Change a file and try to save

## Environment
**OS:** Ubuntu 20.04 focal
**CPU architecture:** x86_64
**How docker service was installed:** apt, from official docker docs

## Command used to create docker container (run/create/compose/screenshot)
The same as your docker hub repo page

## Docker logs
I just see VS Code logs

**Comment by Nefcanto** [comment]
I installed .NET Core on your image and now I also get this error:

> /usr/share/dotnet/sdk/3.1.412/NuGet.targets(557,5): error : Unable to obtain lock file access on '/tmp/NuGetScratch/lock/2da39419e35783aea332ab4d2016b9efcf05f4a3' for operations on '/config/.nuget/NuGet/NuGet.Config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/2da39419e35783aea332ab4d2016b9efcf05f4a3' will allow NuGet to continue. [/FreyaCenter/Customers/Models/Models.csproj]

How can we run your image as root?

**Comment by Nefcanto** [comment]
And I also get this error:

> Unable to create 'launch.json' file inside the '.vscode' folder (Unable to write file 'vscode-remote://0.0.0.0:8443/Company/.vscode/launch.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/Company/.vscode')).

It's all about permissions.

**Comment by Roxedus** [comment]
You yet have to provide good information. We want your container logs, and the compose you used.

**Comment by Nefcanto** [comment]
My compose:

```
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```

As I mentioned above, I have used your docker compoase content. I only commented the optional parts out.
