### ISSUE TITLE
extenstion download failed, timeout!

### ISSUE THREAD

**Issue by dengshenkk** [linuxserver/docker-code-server#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

 selected any one extension like this :

docker-compose logs

code-server    |  INFO Installing extension: ecmel.vscode-html-css
code-server    |   ERR Failed to install extension: ecmel.vscode-html-css connect ETIMEDOUT 172.217.24.208:443
code-server    | rejected promise not handled within 1 second: downloading: connect ETIMEDOUT 172.217.24.208:443
code-server    | stack trace: downloading: connect ETIMEDOUT 172.217.24.208:443
code-server    |     at K.downloadInstallableExtension (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:62920)
code-server    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
code-server    |     at async K.doInstallFromGallery (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:60318)
code-server    | downloading: connect ETIMEDOUT 172.217.24.208:443
code-server    |     at K.downloadInstallableExtension (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:62920)
code-server    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
code-server    |     at async K.doInstallFromGallery (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:60318) {
code-server    |   code: 'downloading'
code-server    | }

------------------------------

## Expected Behavior

installed any extension
## Current Behavior

can't install any extension
## Steps to Reproduce

1. in china, ususl we use vpn proxy connetion [github, gist...like more] domain, in host use proxychains4 to proxy, how use proxy in docker-compose
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

ubuntu 18
## Command used to create docker container (run/create/compose/screenshot)

docker-compose config
docker-compose.yml
```
---
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/shanghai
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=my.example.com #optional
    volumes:
      - /path/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```

## Docker logs

code-server    |  INFO Installing extension: ecmel.vscode-html-css
code-server    |   ERR Failed to install extension: ecmel.vscode-html-css connect ETIMEDOUT 172.217.24.208:443
code-server    | rejected promise not handled within 1 second: downloading: connect ETIMEDOUT 172.217.24.208:443
code-server    | stack trace: downloading: connect ETIMEDOUT 172.217.24.208:443
code-server    |     at K.downloadInstallableExtension (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:62920)
code-server    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
code-server    |     at async K.doInstallFromGallery (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:60318)
code-server    | downloading: connect ETIMEDOUT 172.217.24.208:443
code-server    |     at K.downloadInstallableExtension (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:62920)
code-server    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
code-server    |     at async K.doInstallFromGallery (/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/server/entry.js:41:60318) {
code-server    |   code: 'downloading'
code-server    | }
