### ISSUE TITLE
Container fails to start: Node.js error | PRI4 | Protainer.io

### ISSUE THREAD

**Issue by Kollejoe** [linuxserver/docker-code-server#96]
Hi There,

i'm using this container since a while.
But since a couple of weeks the service stopped with this error:

**Node.js[517]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.**

My other container-> coderaiser/cloudcmd had exact the same error but coderaiser could fix it with a new version. There must be a node base image problem, it seems like updating the base images could fix it!

Environment
UI: Protainer.io
HW: PRI 4
Docker compose yml:
```
version: '2.1'
services:
    vscode:  
        image: lscr.io/linuxserver/code-server
        container_name: vscode
        ports:
            - 8443:8443
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
        volumes:
            - /applications/vscode:/config
        restart: unless-stopped
```

Cheers
Niko
